### ISSUE TITLE
ValueError: 'src/cld3.pyx' doesn't match any files

### ISSUE THREAD

**Issue by KonstantinaLazaridou** [bsolomon1124/pycld3#14]
Hi,

I am installing cld3 with `pip` in an anacoda environment. Initially there was an error that Cyhton could not be found, so I installed Cython. Following the Readme, I also installed `gcc` and `python-protobuf`. I am trying again to install cld3, but I get the following error:

```
pip install cld3
Collecting cld3
  Using cached cld3-0.2.2.tar.gz (593 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/konstantina/anaconda3/envs/myenv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-jbyy1l8u/cld3/setup.py'"'"'; __file__='"'"'/tmp/pip-install-jbyy1l8u/cld3/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-jbyy1l8u/cld3/pip-egg-info
         cwd: /tmp/pip-install-jbyy1l8u/cld3/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-jbyy1l8u/cld3/setup.py", line 98, in <module>
        ext_modules=cythonize([ext]))
      File "/home/konstantina/anaconda3/envs/myenv/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 972, in cythonize
        aliases=aliases)
      File "/home/konstantina/anaconda3/envs/myenv/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 815, in create_extension_list
        for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
      File "/home/konstantina/anaconda3/envs/myenv/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 114, in nonempty
        raise ValueError(error_msg)
    ValueError: 'src/cld3.pyx' doesn't match any files
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
 ```

I am using Manjaro Linux and I also tried installing libprotof, but even though there is a package in the AUR repo, it's not found via pacman. That's what I I tried and it didn't work out: `sudo pacman -S libprotobuf-dev`.

Any idea what to do next? Thanks in advance!

**Comment by bsolomon1124** [comment]
This package is `pycld3`, not `cld3`:

```
python -m pip install -U pycld3
```

You can then `import` it as `cld3`.
