### ISSUE TITLE
AttributeError: module 'cld3' has no attribute 'get_language'

### ISSUE THREAD

**Issue by loretoparisi** [bsolomon1124/pycld3#15]
I get this error while installing to macOS 10.14.5:

```bash
Traceback (most recent call last):
  File "cld3.py", line 11, in <module>
    import cld3
  File "/Users/loretoparisi/Documents/Projects/tests/cld3.py", line 14, in <module>
    cld3.get_language("影響包含對氣候的變化以及自然資源的枯竭程度")
AttributeError: module 'cld3' has no attribute 'get_language'
```

If I try
```bash
ip-192-168-1-168:tests loretoparisi$ python3 -m pip install --no-cache-dir pycld3
Requirement already satisfied: pycld3 in /usr/local/lib/python3.7/site-packages (0.20)
```

**Comment by loretoparisi** [comment]
My fault, it works!
