### ISSUE TITLE
pip install doesn't work

### ISSUE THREAD

**Issue by lpla** [bsolomon1124/pycld3#3]
I am unable to install `pycld3` using `pip` command. Installing with `pip install git+https://github.com/bsolomon1124/pycld3` works fine. Log:

```
$ pip install pycld3
Collecting pycld3
  Using cached https://files.pythonhosted.org/packages/bd/4c/1c2dabc044a660e53c5b33379423f41150f3d99f58ece40fb7a29270578e/pycld3-0.14.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-sph7tlov/pycld3/setup.py", line 141, in <module>
        extensions = cythonize(ext)
      File "/home/lpla/bitextorment/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 966, in cythonize
        aliases=aliases)
      File "/home/lpla/bitextorment/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 810, in create_extension_list
        for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
      File "/home/lpla/bitextorment/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 109, in nonempty
        raise ValueError(error_msg)
    ValueError: 'pycld3.pyx' doesn't match any files
```

**Comment by bsolomon1124** [comment]
Hi @lpla , sorry it has taken me a few days to get to this.  Could you please let me know:

- os/os version, i.e. `lsb_release -a, system_profiler SPSoftwareDataType`, etc
- Python executable version, `python --version`
- Whether you have Cython installed & what version, `python -m cython --version || echo 'cython not found'`

**Comment by nstrel** [comment]
I have the same issue with configuration: Ubuntu 18.04.3 LTS, Python 3.7.5, Cython version 0.29.14

**Comment by lpla** [comment]
Using a clean virtual environment without `cython` makes it work:

```
(testingcld3) lpla@lpla-H110M-DS2:~$ pip3 install pycld3
Collecting pycld3
Installing collected packages: pycld3
Successfully installed pycld3-0.14
(testingcld3) lpla@lpla-H110M-DS2:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
(testingcld3) lpla@lpla-H110M-DS2:~$ python --version
Python 3.6.8
(testingcld3) lpla@lpla-H110M-DS2:~$ python -m cython --version || echo 'cython not found'
/home/lpla/testingcld3/bin/python: No module named cython
cython not found
```

But using an environment I use for the project `bitextor`, which contains `cython`, I get what I posted earlier. If I uninstall `cython` in that exact environment, I get it working:

```
(bitextorment) lpla@lpla-H110M-DS2:~$ pip install pycld3
Collecting pycld3
  Downloading https://files.pythonhosted.org/packages/bd/4c/1c2dabc044a660e53c5b33379423f41150f3d99f58ece40fb7a29270578e/pycld3-0.14.tar.gz (686kB)
     |████████████████████████████████| 696kB 1.1MB/s 
    ERROR: Command errored out with exit status 1:
     command: /home/lpla/bitextorment/bin/python3.6 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-dcfa26n3/pycld3/setup.py'"'"'; __file__='"'"'/tmp/pip-install-dcfa26n3/pycld3/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-dcfa26n3/pycld3/pip-egg-info
         cwd: /tmp/pip-install-dcfa26n3/pycld3/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-dcfa26n3/pycld3/setup.py", line 141, in <module>
        extensions = cythonize(ext)
      File "/home/lpla/bitextorment/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 966, in cythonize
        aliases=aliases)
      File "/home/lpla/bitextorment/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 810, in create_extension_list
        for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
      File "/home/lpla/bitextorment/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 109, in nonempty
        raise ValueError(error_msg)
    ValueError: 'pycld3.pyx' doesn't match any files
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
(bitextorment) lpla@lpla-H110M-DS2:~$ pip uninstall cython
Uninstalling Cython-0.29.13:
  Would remove:
    /home/lpla/bitextorment/bin/cygdb
    /home/lpla/bitextorment/bin/cython
    /home/lpla/bitextorment/bin/cythonize
    /home/lpla/bitextorment/lib/python3.6/site-packages/Cython-0.29.13.dist-info/*
    /home/lpla/bitextorment/lib/python3.6/site-packages/Cython/*
    /home/lpla/bitextorment/lib/python3.6/site-packages/cython.py
    /home/lpla/bitextorment/lib/python3.6/site-packages/pyximport/*
Proceed (y/n)? y
  Successfully uninstalled Cython-0.29.13
(bitextorment) lpla@lpla-H110M-DS2:~$ pip install pycld3
Collecting pycld3
  Using cached https://files.pythonhosted.org/packages/bd/4c/1c2dabc044a660e53c5b33379423f41150f3d99f58ece40fb7a29270578e/pycld3-0.14.tar.gz
Building wheels for collected packages: pycld3
  Building wheel for pycld3 (setup.py) ... done
  Created wheel for pycld3: filename=pycld3-0.14-cp36-cp36m-linux_x86_64.whl size=2298823 sha256=2e23c525eef27d8251432e2031410195b00341a0f59690f540ac8d8f77788f4b
  Stored in directory: /home/lpla/.cache/pip/wheels/5e/16/29/5dd733c7e32cedf8243aeb2fe5eae3056697bdb3c769234e1b
Successfully built pycld3
Installing collected packages: pycld3
Successfully installed pycld3-0.14
(bitextorment) lpla@lpla-H110M-DS2:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
(bitextorment) lpla@lpla-H110M-DS2:~$ python --version
Python 3.6.8
(bitextorment) lpla@lpla-H110M-DS2:~$ python -m cython --version || echo 'cython not found'
/home/lpla/bitextorment/bin/python: No module named cython
cython not found
```

**Comment by bsolomon1124** [comment]
Sorry for the trouble - I had neglected to include the .pyx file in the PyPI MANIFEST.  It is now there, along with the .cpp file, in PyPI version 0.16, and I've tested that installs both with and without Cython (on Python 3.6.9 to be exact) both work.
