### ISSUE TITLE
Incompatibility with protobuf-3.20.1

### ISSUE THREAD

**Issue by bojanbg** [bsolomon1124/pycld3#30]
Apologies if this is not a `pycld3` issue but a `cld3` one. I only use it through the Python bindings.

System upgrade switched `protobuf` to the latest version (3.20.1). After that:
```shell
(.venv) [<redacted>]$ python
Python 3.10.4 (main, Mar 23 2022, 23:05:40) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cld3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/<redacted>/.venv/lib/python3.10/site-packages/cld3/__init__.py", line 3, in <module>
    from ._cld3 import *  # noqa
ImportError: libprotobuf.so.30: cannot open shared object file: No such file or directory
```

Protobuf 3.20.1 publishes `libprotobuf.so.31`.

Reverting to protobuf 3.19.4 resolves the issue, as that package does have `libprotobuf.so.30`.

**Comment by bsolomon1124** [comment]
Thanks for opening this issue, and apologies for the late reply.

This project is being **archived and is no longer maintained**. Please see the [archive notice at the top of `README.md` on `master`](https://github.com/bsolomon1124/pycld3/blob/master/README.md#pycld3) for the reasons and for recommended alternatives (`gcld3`, `lingua-language-detector`, `fasttext`, `pycld2`).

Closing this issue as part of the archival. Sorry I could not get to it sooner, and thanks for your interest in `pycld3`.
