### ISSUE TITLE
Could not build wheels for pycld3, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by mahfuz225bd** [bsolomon1124/pycld3#36]
After `pip install pycld3`:

```powershell
Collecting pycld3
  Using cached pycld3-0.22.tar.gz (726 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: pycld3
  Building wheel for pycld3 (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for pycld3 (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [46 lines of output]
      running bdist_wheel
      running build
      Traceback (most recent call last):
        File "F:\My Apps\Hospital E-Ticketing System\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "F:\My Apps\Hospital E-Ticketing System\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "F:\My Apps\Hospital E-Ticketing System\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\mahfu\AppData\Local\Temp\pip-build-env-brxjr1q3\overlay\Lib\site-packages\setuptools\build_meta.py", line 404, in build_wheel  
          return self._build_with_temp_dir(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\mahfu\AppData\Local\Temp\pip-build-env-brxjr1q3\overlay\Lib\site-packages\setuptools\build_meta.py", line 389, in _build_with_temp_dir
          self.run_setup()
        File "C:\Users\mahfu\AppData\Local\Temp\pip-build-env-brxjr1q3\overlay\Lib\site-packages\setuptools\build_meta.py", line 480, in run_setup    
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "C:\Users\mahfu\AppData\Local\Temp\pip-build-env-brxjr1q3\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup    
          exec(code, locals())
        File "<string>", line 173, in <module>
        File "C:\Users\mahfu\AppData\Local\Temp\pip-build-env-brxjr1q3\overlay\Lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\mahfu\AppData\Local\Temp\pip-build-env-brxjr1q3\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup   
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\Users\mahfu\AppData\Local\Temp\pip-build-env-brxjr1q3\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\mahfu\AppData\Local\Temp\pip-build-env-brxjr1q3\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\mahfu\AppData\Local\Temp\pip-build-env-brxjr1q3\overlay\Lib\site-packages\setuptools\dist.py", line 963, in run_command        
          super().run_command(command)
        File "C:\Users\mahfu\AppData\Local\Temp\pip-build-env-brxjr1q3\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\mahfu\AppData\Local\Temp\pip-build-env-brxjr1q3\overlay\Lib\site-packages\wheel\bdist_wheel.py", line 368, in run
          self.run_command("build")
        File "C:\Users\mahfu\AppData\Local\Temp\pip-build-env-brxjr1q3\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\mahfu\AppData\Local\Temp\pip-build-env-brxjr1q3\overlay\Lib\site-packages\setuptools\dist.py", line 963, in run_command        
          super().run_command(command)
        File "C:\Users\mahfu\AppData\Local\Temp\pip-build-env-brxjr1q3\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 109, in run
      RuntimeError: The Protobuf compiler, `protoc`, which is required for building this package, could not be found.
      See https://github.com/protocolbuffers/protobuf for information on installing Protobuf.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pycld3
Failed to build pycld3
ERROR: Could not build wheels for pycld3, which is required to install pyproject.toml-based projects
```

**Comment by Nevermetyou65** [comment]
same problem here

**Comment by ichhabkeinbock** [comment]
Install protoc using: `sudo apt install -y protobuf-compiler`
But I'm failing to install it after that step due to some missing libraries like longintrepr.h (Cython related).

**Comment by ay2456** [comment]
Successfully installed on python 3.10 with:

```
sudo apt-get install -y \
      libprotobuf-dev \
      protobuf-compiler
```

**Comment by Antalela** [comment]
your answer helped me on google colab but...

> Successfully installed on python 3.10 with:
> 
> ```
> sudo apt-get install -y \
>       libprotobuf-dev \
>       protobuf-compiler
> ```

```sudo apt-get``` it only work on linux machines? I am using windows VS-code, so how can I install these two on my machine, can you please help me?

**Comment by bsolomon1124** [comment]
Thanks for opening this issue, and apologies for the late reply.

This project is being **archived and is no longer maintained**. Please see the [archive notice at the top of `README.md` on `master`](https://github.com/bsolomon1124/pycld3/blob/master/README.md#pycld3) for the reasons and for recommended alternatives (`gcld3`, `lingua-language-detector`, `fasttext`, `pycld2`).

Closing this issue as part of the archival. Sorry I could not get to it sooner, and thanks for your interest in `pycld3`.
