### ISSUE TITLE
Cannot install (windows, anaconda python3.7)

### ISSUE THREAD

**Issue by yjjg1993** [bsolomon1124/pycld3#4]
Hi,

Is there a possible way of installing this package on a windows machine through anaconda? I downloaded the protoc binary from https://github.com/protocolbuffers/protobuf/releases and added it to the system path. I checked that the 'protoc' command worked OK. However, when I installed the package throught the conda command line by 'pip install pycld3', I got the following error:

Building wheels for collected packages: pycld3
  Building wheel for pycld3 (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'D:\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Windows\\TEMP\\pip-install-n6randie\\pycld3\\setup.py'"'"'; __file__='"'"'C:\\Windows\\TEMP\\pip-install-n6randie\\pycld3\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Windows\TEMP\pip-wheel-kr910mxc' --python-tag cp37
       cwd: C:\Windows\TEMP\pip-install-n6randie\pycld3\
  Complete output (168 lines):
  running bdist_wheel
  running build
  Running protoc sentence.proto feature_extractor.proto task_spec.proto --cpp_out=C:\Windows\TEMP\pip-install-n6randie\pycld3\src/cld_3/protos/
  running build_ext
  building 'cld3' extension
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Windows\TEMP\pip-install-n6randie\pycld3\setup.py", line 164, in <module>
      classifiers=CLASSIFIERS,
    File "D:\anaconda3\lib\site-packages\setuptools\__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "D:\anaconda3\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "D:\anaconda3\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "D:\anaconda3\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "D:\anaconda3\lib\site-packages\wheel\bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "D:\anaconda3\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "D:\anaconda3\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Windows\TEMP\pip-install-n6randie\pycld3\setup.py", line 119, in run
      build.run(self)
    File "D:\anaconda3\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "D:\anaconda3\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "D:\anaconda3\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "D:\anaconda3\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
      _build_ext.run(self)
    File "D:\anaconda3\lib\distutils\command\build_ext.py", line 340, in run
      self.build_extensions()
    File "D:\anaconda3\lib\distutils\command\build_ext.py", line 449, in build_extensions
      self._build_extensions_serial()
    File "D:\anaconda3\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
      self.build_extension(ext)
    File "D:\anaconda3\lib\site-packages\setuptools\command\build_ext.py", line 205, in build_extension
      _build_ext.build_extension(self, ext)
    File "D:\anaconda3\lib\distutils\command\build_ext.py", line 534, in build_extension
      depends=ext.depends)
    File "D:\anaconda3\lib\distutils\_msvccompiler.py", line 346, in compile
      self.initialize()
    File "D:\anaconda3\lib\distutils\_msvccompiler.py", line 239, in initialize
      vc_env = _get_vc_env(plat_spec)
    File "D:\anaconda3\lib\site-packages\setuptools\msvc.py", line 171, in msvc14_get_vc_env
      return EnvironmentInfo(plat_spec, vc_min_ver=14.0).return_env()
    File "D:\anaconda3\lib\site-packages\setuptools\msvc.py", line 1620, in return_env
      if self.vs_ver >= 14 and isfile(self.VCRuntimeRedist):
    File "D:\anaconda3\lib\genericpath.py", line 30, in isfile
      st = os.stat(path)
  TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

**Comment by bsolomon1124** [comment]
Thanks for opening this issue, and apologies for the late reply.

This project is being **archived and is no longer maintained**. Please see the [archive notice at the top of `README.md` on `master`](https://github.com/bsolomon1124/pycld3/blob/master/README.md#pycld3) for the reasons and for recommended alternatives (`gcld3`, `lingua-language-detector`, `fasttext`, `pycld2`).

Closing this issue as part of the archival. Sorry I could not get to it sooner, and thanks for your interest in `pycld3`.
